/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables;


import cn.leapcloud.release.platform.dao.entity.Circe;
import cn.leapcloud.release.platform.dao.entity.Keys;
import cn.leapcloud.release.platform.dao.entity.tables.records.AppMysqlRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppMysql extends TableImpl<AppMysqlRecord> {

	private static final long serialVersionUID = -187336228;

	/**
	 * The reference instance of <code>circe.app_mysql</code>
	 */
	public static final AppMysql APP_MYSQL = new AppMysql();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppMysqlRecord> getRecordType() {
		return AppMysqlRecord.class;
	}

	/**
	 * The column <code>circe.app_mysql.id</code>.
	 */
	public final TableField<AppMysqlRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>circe.app_mysql.host_id</code>.
	 */
	public final TableField<AppMysqlRecord, Integer> HOST_ID = createField("host_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>circe.app_mysql.app_name</code>.
	 */
	public final TableField<AppMysqlRecord, String> APP_NAME = createField("app_name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>circe.app_mysql.app_id</code>.
	 */
	public final TableField<AppMysqlRecord, String> APP_ID = createField("app_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>circe.app_mysql.password</code>.
	 */
	public final TableField<AppMysqlRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * Create a <code>circe.app_mysql</code> table reference
	 */
	public AppMysql() {
		this("app_mysql", null);
	}

	/**
	 * Create an aliased <code>circe.app_mysql</code> table reference
	 */
	public AppMysql(String alias) {
		this(alias, APP_MYSQL);
	}

	private AppMysql(String alias, Table<AppMysqlRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppMysql(String alias, Table<AppMysqlRecord> aliased, Field<?>[] parameters) {
		super(alias, Circe.CIRCE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AppMysqlRecord, Integer> getIdentity() {
		return Keys.IDENTITY_APP_MYSQL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppMysqlRecord> getPrimaryKey() {
		return Keys.KEY_APP_MYSQL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppMysqlRecord>> getKeys() {
		return Arrays.<UniqueKey<AppMysqlRecord>>asList(Keys.KEY_APP_MYSQL_PRIMARY, Keys.KEY_APP_MYSQL_APP_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysql as(String alias) {
		return new AppMysql(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AppMysql rename(String name) {
		return new AppMysql(name, null);
	}
}
