/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables;


import cn.leapcloud.release.platform.dao.entity.Keys;
import cn.leapcloud.release.platform.dao.entity.LeapcloudReleasePlatform;
import cn.leapcloud.release.platform.dao.entity.tables.records.ReleaseTaskRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleaseTask extends TableImpl<ReleaseTaskRecord> {

	private static final long serialVersionUID = 1996092334;

	/**
	 * The reference instance of <code>leapcloud_release_platform.release_task</code>
	 */
	public static final ReleaseTask RELEASE_TASK = new ReleaseTask();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReleaseTaskRecord> getRecordType() {
		return ReleaseTaskRecord.class;
	}

	/**
	 * The column <code>leapcloud_release_platform.release_task.id</code>.
	 */
	public final TableField<ReleaseTaskRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.release_type</code>.
	 */
	public final TableField<ReleaseTaskRecord, Integer> RELEASE_TYPE = createField("release_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.title</code>.
	 */
	public final TableField<ReleaseTaskRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.project_location</code>.
	 */
	public final TableField<ReleaseTaskRecord, String> PROJECT_LOCATION = createField("project_location", org.jooq.impl.SQLDataType.VARCHAR.length(80), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.project_desc</code>.
	 */
	public final TableField<ReleaseTaskRecord, String> PROJECT_DESC = createField("project_desc", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.proposal</code>.
	 */
	public final TableField<ReleaseTaskRecord, String> PROPOSAL = createField("proposal", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.proposal_time</code>.
	 */
	public final TableField<ReleaseTaskRecord, Timestamp> PROPOSAL_TIME = createField("proposal_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_task.update_time</code>. 更新这个字段,当状态改变的时候
	 */
	public final TableField<ReleaseTaskRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新这个字段,当状态改变的时候");

	/**
	 * The column <code>leapcloud_release_platform.release_task.wDONEstatus</code>. project status,0:wait, 1:done, 2:fail, 3:discard
	 */
	public final TableField<ReleaseTaskRecord, Byte> WDONESTATUS = createField("wDONEstatus", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "project status,0:wait, 1:done, 2:fail, 3:discard");

	/**
	 * The column <code>leapcloud_release_platform.release_task.release_remark</code>.
	 */
	public final TableField<ReleaseTaskRecord, String> RELEASE_REMARK = createField("release_remark", org.jooq.impl.SQLDataType.VARCHAR.length(150), this, "");

	/**
	 * Create a <code>leapcloud_release_platform.release_task</code> table reference
	 */
	public ReleaseTask() {
		this("release_task", null);
	}

	/**
	 * Create an aliased <code>leapcloud_release_platform.release_task</code> table reference
	 */
	public ReleaseTask(String alias) {
		this(alias, RELEASE_TASK);
	}

	private ReleaseTask(String alias, Table<ReleaseTaskRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReleaseTask(String alias, Table<ReleaseTaskRecord> aliased, Field<?>[] parameters) {
		super(alias, LeapcloudReleasePlatform.LEAPCLOUD_RELEASE_PLATFORM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ReleaseTaskRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RELEASE_TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReleaseTaskRecord> getPrimaryKey() {
		return Keys.KEY_RELEASE_TASK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReleaseTaskRecord>> getKeys() {
		return Arrays.<UniqueKey<ReleaseTaskRecord>>asList(Keys.KEY_RELEASE_TASK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTask as(String alias) {
		return new ReleaseTask(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ReleaseTask rename(String name) {
		return new ReleaseTask(name, null);
	}
}
