/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables;


import cn.leapcloud.release.platform.dao.entity.Keys;
import cn.leapcloud.release.platform.dao.entity.LeapcloudReleasePlatform;
import cn.leapcloud.release.platform.dao.entity.tables.records.ReleaseTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleaseType extends TableImpl<ReleaseTypeRecord> {

	private static final long serialVersionUID = 1762683721;

	/**
	 * The reference instance of <code>leapcloud_release_platform.release_type</code>
	 */
	public static final ReleaseType RELEASE_TYPE = new ReleaseType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReleaseTypeRecord> getRecordType() {
		return ReleaseTypeRecord.class;
	}

	/**
	 * The column <code>leapcloud_release_platform.release_type.id</code>.
	 */
	public final TableField<ReleaseTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>leapcloud_release_platform.release_type.name</code>.
	 */
	public final TableField<ReleaseTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * Create a <code>leapcloud_release_platform.release_type</code> table reference
	 */
	public ReleaseType() {
		this("release_type", null);
	}

	/**
	 * Create an aliased <code>leapcloud_release_platform.release_type</code> table reference
	 */
	public ReleaseType(String alias) {
		this(alias, RELEASE_TYPE);
	}

	private ReleaseType(String alias, Table<ReleaseTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReleaseType(String alias, Table<ReleaseTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, LeapcloudReleasePlatform.LEAPCLOUD_RELEASE_PLATFORM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ReleaseTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RELEASE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReleaseTypeRecord> getPrimaryKey() {
		return Keys.KEY_RELEASE_TYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReleaseTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<ReleaseTypeRecord>>asList(Keys.KEY_RELEASE_TYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseType as(String alias) {
		return new ReleaseType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ReleaseType rename(String name) {
		return new ReleaseType(name, null);
	}
}
