/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity;


import cn.leapcloud.release.platform.dao.entity.tables.AppMysql;
import cn.leapcloud.release.platform.dao.entity.tables.MysqlHost;
import cn.leapcloud.release.platform.dao.entity.tables.records.AppMysqlRecord;
import cn.leapcloud.release.platform.dao.entity.tables.records.MysqlHostRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>circe</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AppMysqlRecord, Integer> IDENTITY_APP_MYSQL = Identities0.IDENTITY_APP_MYSQL;
	public static final Identity<MysqlHostRecord, Integer> IDENTITY_MYSQL_HOST = Identities0.IDENTITY_MYSQL_HOST;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AppMysqlRecord> KEY_APP_MYSQL_PRIMARY = UniqueKeys0.KEY_APP_MYSQL_PRIMARY;
	public static final UniqueKey<AppMysqlRecord> KEY_APP_MYSQL_APP_ID = UniqueKeys0.KEY_APP_MYSQL_APP_ID;
	public static final UniqueKey<MysqlHostRecord> KEY_MYSQL_HOST_PRIMARY = UniqueKeys0.KEY_MYSQL_HOST_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AppMysqlRecord, Integer> IDENTITY_APP_MYSQL = createIdentity(AppMysql.APP_MYSQL, AppMysql.APP_MYSQL.ID);
		public static Identity<MysqlHostRecord, Integer> IDENTITY_MYSQL_HOST = createIdentity(MysqlHost.MYSQL_HOST, MysqlHost.MYSQL_HOST.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AppMysqlRecord> KEY_APP_MYSQL_PRIMARY = createUniqueKey(AppMysql.APP_MYSQL, AppMysql.APP_MYSQL.ID);
		public static final UniqueKey<AppMysqlRecord> KEY_APP_MYSQL_APP_ID = createUniqueKey(AppMysql.APP_MYSQL, AppMysql.APP_MYSQL.APP_ID);
		public static final UniqueKey<MysqlHostRecord> KEY_MYSQL_HOST_PRIMARY = createUniqueKey(MysqlHost.MYSQL_HOST, MysqlHost.MYSQL_HOST.ID);
	}
}
