/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity;


import cn.leapcloud.release.platform.dao.entity.tables.ReleaseTask;
import cn.leapcloud.release.platform.dao.entity.tables.ReleaseType;
import cn.leapcloud.release.platform.dao.entity.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeapcloudReleasePlatform extends SchemaImpl {

	private static final long serialVersionUID = -1638938301;

	/**
	 * The reference instance of <code>leapcloud_release_platform</code>
	 */
	public static final LeapcloudReleasePlatform LEAPCLOUD_RELEASE_PLATFORM = new LeapcloudReleasePlatform();

	/**
	 * No further instances allowed
	 */
	private LeapcloudReleasePlatform() {
		super("leapcloud_release_platform");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ReleaseTask.RELEASE_TASK,
			ReleaseType.RELEASE_TYPE,
			User.USER);
	}
}
