/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity;


import cn.leapcloud.release.platform.dao.entity.tables.AppMysql;
import cn.leapcloud.release.platform.dao.entity.tables.MysqlHost;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in circe
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table circe.app_mysql
	 */
	public static final AppMysql APP_MYSQL = cn.leapcloud.release.platform.dao.entity.tables.AppMysql.APP_MYSQL;

	/**
	 * The table circe.mysql_host
	 */
	public static final MysqlHost MYSQL_HOST = cn.leapcloud.release.platform.dao.entity.tables.MysqlHost.MYSQL_HOST;
}
