/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables.records;


import cn.leapcloud.release.platform.dao.entity.tables.AppMysql;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppMysqlRecord extends UpdatableRecordImpl<AppMysqlRecord> implements Record5<Integer, Integer, String, String, String> {

	private static final long serialVersionUID = 2009930815;

	/**
	 * Setter for <code>circe.app_mysql.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>circe.app_mysql.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>circe.app_mysql.host_id</code>.
	 */
	public void setHostId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>circe.app_mysql.host_id</code>.
	 */
	public Integer getHostId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>circe.app_mysql.app_name</code>.
	 */
	public void setAppName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>circe.app_mysql.app_name</code>.
	 */
	public String getAppName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>circe.app_mysql.app_id</code>.
	 */
	public void setAppId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>circe.app_mysql.app_id</code>.
	 */
	public String getAppId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>circe.app_mysql.password</code>.
	 */
	public void setPassword(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>circe.app_mysql.password</code>.
	 */
	public String getPassword() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AppMysql.APP_MYSQL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AppMysql.APP_MYSQL.HOST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppMysql.APP_MYSQL.APP_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AppMysql.APP_MYSQL.APP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return AppMysql.APP_MYSQL.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getHostId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAppName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAppId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord value2(Integer value) {
		setHostId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord value3(String value) {
		setAppName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord value4(String value) {
		setAppId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord value5(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppMysqlRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppMysqlRecord
	 */
	public AppMysqlRecord() {
		super(AppMysql.APP_MYSQL);
	}

	/**
	 * Create a detached, initialised AppMysqlRecord
	 */
	public AppMysqlRecord(Integer id, Integer hostId, String appName, String appId, String password) {
		super(AppMysql.APP_MYSQL);

		setValue(0, id);
		setValue(1, hostId);
		setValue(2, appName);
		setValue(3, appId);
		setValue(4, password);
	}
}
