/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables.records;


import cn.leapcloud.release.platform.dao.entity.tables.MysqlHost;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MysqlHostRecord extends UpdatableRecordImpl<MysqlHostRecord> implements Record8<Integer, String, String, Byte, Integer, Integer, Integer, Byte> {

	private static final long serialVersionUID = 1386614900;

	/**
	 * Setter for <code>circe.mysql_host.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>circe.mysql_host.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>circe.mysql_host.address</code>.
	 */
	public void setAddress(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>circe.mysql_host.is_default</code>.
	 */
	public void setIsDefault(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.is_default</code>.
	 */
	public Byte getIsDefault() {
		return (Byte) getValue(3);
	}

	/**
	 * Setter for <code>circe.mysql_host.master_id</code>.
	 */
	public void setMasterId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.master_id</code>.
	 */
	public Integer getMasterId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>circe.mysql_host.backup_id</code>.
	 */
	public void setBackupId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.backup_id</code>.
	 */
	public Integer getBackupId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>circe.mysql_host.slave_id</code>.
	 */
	public void setSlaveId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.slave_id</code>.
	 */
	public Integer getSlaveId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>circe.mysql_host.type</code>. host type,0:master, 1:backup, 2:slave
	 */
	public void setType(Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>circe.mysql_host.type</code>. host type,0:master, 1:backup, 2:slave
	 */
	public Byte getType() {
		return (Byte) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, Byte, Integer, Integer, Integer, Byte> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, String, String, Byte, Integer, Integer, Integer, Byte> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return MysqlHost.MYSQL_HOST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return MysqlHost.MYSQL_HOST.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return MysqlHost.MYSQL_HOST.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return MysqlHost.MYSQL_HOST.IS_DEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return MysqlHost.MYSQL_HOST.MASTER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return MysqlHost.MYSQL_HOST.BACKUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return MysqlHost.MYSQL_HOST.SLAVE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field8() {
		return MysqlHost.MYSQL_HOST.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getIsDefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getMasterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getBackupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getSlaveId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value8() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value3(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value4(Byte value) {
		setIsDefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value5(Integer value) {
		setMasterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value6(Integer value) {
		setBackupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value7(Integer value) {
		setSlaveId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord value8(Byte value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MysqlHostRecord values(Integer value1, String value2, String value3, Byte value4, Integer value5, Integer value6, Integer value7, Byte value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MysqlHostRecord
	 */
	public MysqlHostRecord() {
		super(MysqlHost.MYSQL_HOST);
	}

	/**
	 * Create a detached, initialised MysqlHostRecord
	 */
	public MysqlHostRecord(Integer id, String name, String address, Byte isDefault, Integer masterId, Integer backupId, Integer slaveId, Byte type) {
		super(MysqlHost.MYSQL_HOST);

		setValue(0, id);
		setValue(1, name);
		setValue(2, address);
		setValue(3, isDefault);
		setValue(4, masterId);
		setValue(5, backupId);
		setValue(6, slaveId);
		setValue(7, type);
	}
}
