/**
 * This class is generated by jOOQ
 */
package cn.leapcloud.release.platform.dao.entity.tables.records;


import cn.leapcloud.release.platform.dao.entity.tables.ReleaseTask;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReleaseTaskRecord extends UpdatableRecordImpl<ReleaseTaskRecord> implements Record11<Integer, Integer, String, String, String, String, Timestamp, Timestamp, Byte, String, String> {

	private static final long serialVersionUID = 1283131405;

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.release_type</code>.
	 */
	public void setReleaseType(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.release_type</code>.
	 */
	public Integer getReleaseType() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.title</code>.
	 */
	public void setTitle(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.project_location</code>.
	 */
	public void setProjectLocation(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.project_location</code>.
	 */
	public String getProjectLocation() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.project_desc</code>.
	 */
	public void setProjectDesc(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.project_desc</code>.
	 */
	public String getProjectDesc() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.proposal</code>.
	 */
	public void setProposal(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.proposal</code>.
	 */
	public String getProposal() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.proposal_time</code>.
	 */
	public void setProposalTime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.proposal_time</code>.
	 */
	public Timestamp getProposalTime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.update_time</code>. 更新这个字段,当状态改变的时候
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.update_time</code>. 更新这个字段,当状态改变的时候
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.status</code>. project status,0:wait, 1:done, 2:fail, 3:discard
	 */
	public void setStatus(Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.status</code>. project status,0:wait, 1:done, 2:fail, 3:discard
	 */
	public Byte getStatus() {
		return (Byte) getValue(8);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.release_remark</code>.
	 */
	public void setReleaseRemark(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.release_remark</code>.
	 */
	public String getReleaseRemark() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>leapcloud_release_platform.release_task.tag</code>.
	 */
	public void setTag(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>leapcloud_release_platform.release_task.tag</code>.
	 */
	public String getTag() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, String, String, String, String, Timestamp, Timestamp, Byte, String, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, String, String, String, String, Timestamp, Timestamp, Byte, String, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ReleaseTask.RELEASE_TASK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return ReleaseTask.RELEASE_TASK.RELEASE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return ReleaseTask.RELEASE_TASK.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return ReleaseTask.RELEASE_TASK.PROJECT_LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return ReleaseTask.RELEASE_TASK.PROJECT_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return ReleaseTask.RELEASE_TASK.PROPOSAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return ReleaseTask.RELEASE_TASK.PROPOSAL_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return ReleaseTask.RELEASE_TASK.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field9() {
		return ReleaseTask.RELEASE_TASK.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return ReleaseTask.RELEASE_TASK.RELEASE_REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return ReleaseTask.RELEASE_TASK.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getReleaseType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getProjectLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getProjectDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getProposal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getProposalTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value9() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getReleaseRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value2(Integer value) {
		setReleaseType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value3(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value4(String value) {
		setProjectLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value5(String value) {
		setProjectDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value6(String value) {
		setProposal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value7(Timestamp value) {
		setProposalTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value8(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value9(Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value10(String value) {
		setReleaseRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord value11(String value) {
		setTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReleaseTaskRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8, Byte value9, String value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReleaseTaskRecord
	 */
	public ReleaseTaskRecord() {
		super(ReleaseTask.RELEASE_TASK);
	}

	/**
	 * Create a detached, initialised ReleaseTaskRecord
	 */
	public ReleaseTaskRecord(Integer id, Integer releaseType, String title, String projectLocation, String projectDesc, String proposal, Timestamp proposalTime, Timestamp updateTime, Byte status, String releaseRemark, String tag) {
		super(ReleaseTask.RELEASE_TASK);

		setValue(0, id);
		setValue(1, releaseType);
		setValue(2, title);
		setValue(3, projectLocation);
		setValue(4, projectDesc);
		setValue(5, proposal);
		setValue(6, proposalTime);
		setValue(7, updateTime);
		setValue(8, status);
		setValue(9, releaseRemark);
		setValue(10, tag);
	}
}
